#!/usr/bin/env bash

player_status=$(playerctl status)
if [ -z $player_status ]; then exit 1; fi
if [ $player_status = "Stopped" ]; then
	printf "⏹\\n⏹\\n#073642"
else
	title=$(playerctl metadata title)
	echo "$title - $(playerctl metadata artist)"
	[ $player_status = "Paused" ] && printf %s\\n%s "⏸" "#cccc00" || echo "⏵"
fi

case $BLOCK_BUTTON in
  3) playerctl play-pause ;;  # right click, play/pause
esac
